### ISSUE TITLE
랜덤 가게 추천

### ISSUE THREAD

**Issue by TaeJuneJoung** [dldurhks12/Alcohol-Free#4]
# 랜덤 가게 추천

- 카테고리별 고른 거에 따라서 가게 추천

- or 형식으로 카테고리 고른거에 속하면 다 포함

**html ex**
```html
<div>
  <input type="checkbox" name="category" value="1" />안주가 맛있는
  <input type="checkbox" name="category" value="2" />20대
  <input type="checkbox" name="category" value="3" />30대
  <input type="checkbox" name="category" value="4" />40대
  <input type="checkbox" name="category" value="5" />50대
</div>
<button class="btn">랜덤 추천</button>
<div class="loader d-none"></div>
<div id="pick-place"></div>
```

**css ex**
```css
* {
  box-sizing: border-box;
}
.loader {
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid gray;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 1.5s linear infinite; /* Safari */
  animation: spin 1.5s linear infinite;
}

/* Safari */
@-webkit-keyframes spin {
  0% {
    -webkit-transform: rotate(0deg);
  }
  100% {
    -webkit-transform: rotate(360deg);
  }
}

@keyframes spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
.btn {
  width: 150px;
  height: 70px;
  background-color: lightgreen;
  border: 1px solid lightgreen;
  border-radius: 0.5rem;
  margin-top: 3rem;
  margin-bottom: 3rem;
}
.btn:hover {
  background-color: rgb(93, 177, 93);
  border: 1px solid rgb(93, 177, 93);
  border-radius: 0.5rem;
  margin-top: 3rem;
  margin-bottom: 3rem;
}
.btn:active {
  color: white;
  background-color: green;
  border: 1px solid green;
  border-radius: 0.5rem;
  margin-top: 3rem;
  margin-bottom: 3rem;
}
.d-none {
  display: none;
}
```

**js ex**
```javascript
const places = [
  ["주기", [1, 4]],
  ["구기", [3]],
  ["역전할머니맥주", [2, 3]],
  ["다사랑치킨", [4]],
  ["대장군막걸리", [5]],
];

document.querySelector(".btn").addEventListener("click", ({ target }) => {
  document.getElementById("pick-place").innerText = "";
  const selectList = [];
  const checkList = document.getElementsByName("category");
  checkList.forEach((check) => {
    if (check.checked) {
      selectList.push(parseInt(check.value));
    }
  });
  let suitablePlace = [];
  selectList.map((select) => {
    places.map((place) => {
      if (place[1].includes(select) === true) {
        suitablePlace.push(place);
      }
    });
  });
  const uniqueSuitablePlace = [...new Set(suitablePlace)];
  const loader = document.querySelector(".loader");
  loader.classList.remove("d-none");
  setTimeout(() => {
    const pickIndex = Math.floor(
      Math.random() * uniqueSuitablePlace.length
    );
    const pickPlace = uniqueSuitablePlace[pickIndex];
    loader.classList.add("d-none");
    document.getElementById("pick-place").innerText = pickPlace[0];
  }, 3000);
});
````
